name: Build and Push Docker Image
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for aarch64 architecture only
        uses: docker/build-push-action@v3
        with:
          context: .
          file: scripts/Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: |
            blu7812/sub-ver:aarch64-latest

