name: Build and Push Docker Image using Binary
on:
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download binary artifact
        uses: actions/download-artifact@v2
        with:
          name: subconverter_aarch64.tar.gz

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for aarch64 architecture only
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.binary
          platforms: linux/arm64/v8
          push: true
          tags: |
            blu7812/sub-ver:aarch64-latest

