name: Build Binary
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  aarch64_build:
     name: Linux aarch64 Build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
       - name: Add commit id into version
         if: ${{ !startsWith(github.ref, 'refs/tags/') }}
         run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
       - name: Build
         run: docker run -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:aarch64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
       - name: Package Release
         run: tar czf subconverter_aarch64.tar.gz subconverter

       - name: Upload
         uses: actions/upload-artifact@v3
         with:
           path: |
             subconverter_*.tar.gz

       - name: Draft Release
         uses: softprops/action-gh-release@v1
         if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
         with:
           files: subconverter_aarch64.tar.gz
           draft: true
           tag_name: Alpha

